config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homes#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  resources :homes

  resources :newfeeds

  resources :banners

  resources :users do
  end

  resources :news do
  end

  resources :article_stores do
    resources :articles
  end

  resources :book_stores do
    resources :books
  end

  resources :lecture_stores do
    resources :lectures
  end

  resources :rule_stores do
    resources :rules
  end

  resources :photo_stores do
    resources :albums do
      resources :photos
    end
  end

  resources :others do
    resources :other_items do
      resources :other_item_details
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :photo_store
  has_many :photos, :dependent => :destroy
  has_many :newfeeds, :dependent => :destroy
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :article_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :book_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/book_store.rb
class BookStore < ActiveRecord::Base
  has_many :books, :dependent => :destroy
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :lecture_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/newfeed.rb
class Newfeed < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  has_many :newfeeds, :dependent => :destroy
end

app/models/other.rb
class Other < ActiveRecord::Base
  has_many :other_items, :dependent => :destroy
end

app/models/other_item.rb
class OtherItem < ActiveRecord::Base
  has_many :other_item_details, :dependent => :destroy
  belongs_to :other
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :url, PictureUploader
  belongs_to :album

  def next album_id
    Photo.where(album_id: album_id).where("photos.id > ? ", self.id).order("photos.id ASC").limit(1)
  end

  def previous album_id
    Photo.where(album_id: album_id).where("photos.id < ?", self.id).order("photos.id DESC").limit(1)
end

end

app/models/photo_store.rb
class PhotoStore < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :rule_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/rule_store.rb
class RuleStore < ActiveRecord::Base
  has_many :rules, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save   :downcase_email
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/newfeeds_controller.rb
class NewfeedsController < ApplicationController
  def index
    @newfeeds = Newfeed.order('created_at DESC').paginate(page: params[:page], per_page: 15)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_feeds_helper.rb
module NewFeedsHelper
end

app/helpers/newfeeds_helper.rb
module NewfeedsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/newfeeds/index.html.erb
<ol class="breadcrumb">
  <li class="active">Bài mới
  </li>

</ol>
<div class="jumbotron bg_white_color">
<% @newfeeds.each do |newfeed| %>
  <% if !newfeed.news_id.to_s.empty? %>
  <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
     <%= "[Tin tức]" %>
     <% @news = News.find(newfeed.news_id) %>
     <%= link_to @news.name, news_path(@news)%>
     <h6>
       <em>
       <small ><%= @news.created_at.to_date %></small>
       </em>
     </h6>
     <hr>
  <% elsif !newfeed.lecture_id.to_s.empty?%>
  <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
    <%= "[Bài Giảng]" %>
    <% @lecture = Lecture.find(newfeed.lecture_id) %>
    <%= link_to @lecture.name, lecture_store_lecture_path(@lecture.lecture_store, @lecture)%>
         <h6>
       <em>
       <small ><%= @lecture.created_at.to_date %></small>
       </em>
     </h6>
    <hr>
  <% elsif !newfeed.book_id.to_s.empty?%>
    <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
    <%= "[Kinh]" %>
    <% @book = Book.find(newfeed.book_id) %>
    <%= link_to @book.name, book_store_book_path(@book.book_store, @book)%>
         <h6>
       <em>
       <small ><%= @book.created_at.to_date %></small>
       </em>
     </h6>
    <hr>
  <% elsif !newfeed.rule_id.to_s.empty?%>
    <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
    <%= "[Luật]" %>
    <% @rule = Rule.find(newfeed.rule_id) %>
    <%= link_to @rule.name, rule_store_rule_path(@rule.rule_store, @rule)%>
         <h6>
       <em>
       <small ><%= @rule.created_at.to_date %></small>
       </em>
     </h6>
    <hr>
  <% elsif !newfeed.article_id.to_s.empty?%>
    <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
    <%= "[Luận]" %>
    <% @article = Article.find(newfeed.article_id) %>
    <%= link_to @article.name, article_store_article_path(@article.article_store, @article)%>
         <h6>
       <em>
       <small ><%= @article.created_at.to_date %></small>
       </em>
     </h6>
    <hr>
  <% elsif !newfeed.album_id.to_s.empty?%>
    <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
    <%= "[Hình ảnh]" %>
    <% @album = Album.find(newfeed.album_id) %>
    <%= link_to @album.name, photo_store_album_path(@album.photo_store, @album)%>
         <h6>
       <em>
       <small ><%= @album.created_at.to_date %></small>
       </em>
     </h6>
    <hr>
  <% elsif !newfeed.other_item_detail_id.to_s.empty?%>
    <% @other_item_detail = OtherItemDetail.find(newfeed.other_item_detail_id) %>
      <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
    <%= "[#{@other_item_detail.other_item.name}]" %>
    <%= link_to @other_item_detail.name, other_other_item_other_item_detail_path(@other_item_detail.other_item.other, @other_item_detail.other_item, @other_item_detail)%>
         <h6>
       <em>
       <small ><%= @other_item_detail.created_at.to_date %></small>
       </em>
     </h6>
     <hr>
  <% end %>
<% end %>
</div>

  <div class="container">
    <%= will_paginate @newfeeds%>
  </div>