config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homes#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  resources :homes

  resources :newfeeds

  resources :banners

  resources :users do
  end

  resources :news do
  end

  resources :article_stores do
    resources :articles
  end

  resources :book_stores do
    resources :books
  end

  resources :lecture_stores do
    resources :lectures
  end

  resources :rule_stores do
    resources :rules
  end

  resources :photo_stores do
    resources :albums do
      resources :photos
    end
  end

  resources :others do
    resources :other_items do
      resources :other_item_details
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :photo_store
  has_many :photos, :dependent => :destroy
  has_many :newfeeds, :dependent => :destroy
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :article_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/article_store.rb
class ArticleStore < ActiveRecord::Base
  has_many :articles, :dependent => :destroy
end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :book_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/book_store.rb
class BookStore < ActiveRecord::Base
  has_many :books, :dependent => :destroy
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :lecture_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/newfeed.rb
class Newfeed < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  has_many :newfeeds, :dependent => :destroy
end

app/models/other.rb
class Other < ActiveRecord::Base
  has_many :other_items, :dependent => :destroy
end

app/models/other_item.rb
class OtherItem < ActiveRecord::Base
  has_many :other_item_details, :dependent => :destroy
  belongs_to :other
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :url, PictureUploader
  belongs_to :album

  def next album_id
    Photo.where(album_id: album_id).where("photos.id > ? ", self.id).order("photos.id ASC").limit(1)
  end

  def previous album_id
    Photo.where(album_id: album_id).where("photos.id < ?", self.id).order("photos.id DESC").limit(1)
end

end

app/models/photo_store.rb
class PhotoStore < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :rule_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/rule_store.rb
class RuleStore < ActiveRecord::Base
  has_many :rules, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save   :downcase_email
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/article_stores_controller.rb
class ArticleStoresController < ApplicationController
 def index
 end

 def new
 	@article_store = ArticleStore.new
 end

def create
  @article_store = ArticleStore.new article_store_params
  if @article_store.save
    redirect_to root_path
  else
    flash[:danger] = "Create fails, please retry."
    render 'new'
  end
end

def show
  @article_store = ArticleStore.find params[:id]
  @articles = @article_store.articles.order('created_at DESC').paginate(page: params[:page], per_page: 10)
end

def edit
  @article_store = ArticleStore.find params[:id]
end

def update
  @article_store = ArticleStore.find params[:id]
  if @article_store.update_attributes article_store_params
      redirect_to article_store_path(@article_store)
  else
      render 'edit'
  end
end

def destroy
  @article_store = ArticleStore.find params[:id]
  @article_store.destroy
  redirect_to root_path
end

private
def article_store_params
  params.require(:article_store).permit(:name, :description)
end

end

app/helpers/article_stores_helper.rb
module ArticleStoresHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/article_stores/edit.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for @article_store, method: :patch do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_area :description, class: "form-control",
                                  placeholder: "Description" %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/article_stores/new.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for @article_store do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_area :description, class: "form-control",
                                  placeholder: "Description" %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/article_stores/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Luận"%></li>
  <li>
    <%= @article_store.name%>
  </li>
</ol>

<% if logged_in? %>
<div class="bs-example">
    <ul class="nav nav-pills" role="tablist">
      <li role="presentation" class="dropdown">
        <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
          Action
          <span class="caret"></span>
        </a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
          <li role="presentation">
              <%= link_to "Add articles",  new_article_store_article_path(@article_store)%>
          </li>
          <li role="presentation">
            <%= link_to "Edit",  edit_article_store_path(@article_store)%>
          </li>
          <li role="presentation">
            <%= link_to "Delete", article_store_path(@article_store),
                    method: :delete,
                    data: { confirm: 'Make sure you want to do this?' }%>
          </li>
          <li role="presentation" class="divider"></li>
          <li role="presentation">
          	
          </li>
        </ul>
      </li>
    </ul> <!-- /pills -->
  </div>
<% end %>

<div class="breadcrumb_retative">
<ol class="breadcrumb breadcrumb_retative bg_breadcrumb">
  <li><%= link_to "Bài liên quan"%></li>
  </ol>
<div class=" bg_white_color breadcrumb_retative">
<% @article_store.articles.sample(10).each do |article| %>
  <div class="thumbnail caption news_title_thumnail">
  <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
     <%= link_to article.name, article_store_article_path(article.article_store, article) %>
    <div class="small_info_time">
     <%= article.created_at.to_date %>
   </div>
   </div>
<hr>
<% end %>
</div>
</div>

<%= render @article_store.articles.order('created_at DESC') %>

<div class="thumbnail thumbnail_w_h_news_container" data-example-id="simple-thumbnails">
    <%= will_paginate @articles %>
</div>