config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homes#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  resources :homes

  resources :newfeeds

  resources :banners

  resources :users do
  end

  resources :news do
  end

  resources :article_stores do
    resources :articles
  end

  resources :book_stores do
    resources :books
  end

  resources :lecture_stores do
    resources :lectures
  end

  resources :rule_stores do
    resources :rules
  end

  resources :photo_stores do
    resources :albums do
      resources :photos
    end
  end

  resources :others do
    resources :other_items do
      resources :other_item_details
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :photo_store
  has_many :photos, :dependent => :destroy
  has_many :newfeeds, :dependent => :destroy
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :article_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :book_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/book_store.rb
class BookStore < ActiveRecord::Base
  has_many :books, :dependent => :destroy
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :lecture_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/newfeed.rb
class Newfeed < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  has_many :newfeeds, :dependent => :destroy
end

app/models/other.rb
class Other < ActiveRecord::Base
  has_many :other_items, :dependent => :destroy
end

app/models/other_item.rb
class OtherItem < ActiveRecord::Base
  has_many :other_item_details, :dependent => :destroy
  belongs_to :other
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :url, PictureUploader
  belongs_to :album

  def next album_id
    Photo.where(album_id: album_id).where("photos.id > ? ", self.id).order("photos.id ASC").limit(1)
  end

  def previous album_id
    Photo.where(album_id: album_id).where("photos.id < ?", self.id).order("photos.id DESC").limit(1)
end

end

app/models/photo_store.rb
class PhotoStore < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :rule_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/rule_store.rb
class RuleStore < ActiveRecord::Base
  has_many :rules, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save   :downcase_email
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/other_items_controller.rb
class OtherItemsController < ApplicationController
 def new
   @other = Other.find params[:other_id]
 end

 def create
    @other = Other.find params[:other_id]
    @other_item = @other.other_items.create other_item_params
    redirect_to root_path
 end

 def show
    @other = Other.find params[:other_id]
    @other_item = OtherItem.find params[:id]
    @other_item_details = @other_item.other_item_details
 end

 def edit
    @other_item = OtherItem.find params[:id]
 end

 def update
   @other_item = OtherItem.find params[:id]
    if @other_item.update_attributes other_item_params
      redirect_to other_other_item_path(@other_item.other, @other_item)
    else
      render 'edit'
    end
 end

 def destroy
    @other_item = OtherItem.find params[:id]
    @other_item.destroy
    redirect_to root_path
 end

  private
  def other_item_params
    params.require(:other_item).permit(:name)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/other_items_helper.rb
module OtherItemsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/other_items/edit.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for :other_item, url: other_other_item_path , method: :patch do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
        placeholder: @other_item.name %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/other_items/new.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for [@other, @other.other_items.build] do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/other_items/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Mục khác"%></li>
  <li><%= link_to @other_item.other.name,"" %></li>
  <li>
    <%= @other_item.name %>
  </li>
</ol>

<% if logged_in? %>
<div class="bs-example">
    <ul class="nav nav-pills" role="tablist">
      <li role="presentation" class="dropdown">
        <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
          Action
          <span class="caret"></span>
        </a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
          <li role="presentation">
              <%= link_to "Add items", new_other_other_item_other_item_detail_path(@other, @other_item) %>
          </li>
          <li role="presentation">
           <%= link_to "Edit.", edit_other_other_item_path(@other, @other_item) %>
          </li>
          <li role="presentation">
              <%= link_to "Delete.", other_other_item_path(@other, @other_item),
                    method: :delete,
                    data: { confirm: 'Make sure you want to do this?' }%>
          </li>
          <li role="presentation" class="divider"></li>
          <li role="presentation">
            
          </li>
        </ul>
      </li>
    </ul> <!-- /pills -->
  </div>
<% end %>

  <% @other_item_details.each do |other_item_detail| %>
<div class="bs-example" data-example-id="simple-thumbnails">
    <div class="thumbnail thumbnail_w_h">
      <%= link_to (image_tag other_item_detail.url, width: "100%"), other_other_item_other_item_detail_path(@other, @other_item, other_item_detail )%>
      <div class="caption center">
      <h6>
        <%= link_to other_item_detail.name, other_other_item_other_item_detail_path(@other, @other_item, other_item_detail) %>
        <%= other_item_detail.description %>
        </h6>
      </div>
    </div>
 </div> 
<% end %>